---
- name: Create SQL 2019 Install Script
  ansible.windows.win_template:
    src: installSQL2019.bat
    dest: C:\installSQL2019.bat

- name: Install SQL 2019
  ansible.windows.win_shell: c:\installSQL2019.bat
  args:
    executable: cmd
    chdir: c:\
    creates: c:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER
