---
- name: Create config file
  ansible.windows.win_template:
    src: sqlsilent.ini
    dest: c:\sqlsilent.ini

- name: Install SQL2019
  ansible.windows.win_shell: "{{ disk_image_out.mount_paths[0] }}setup.exe /ConfigurationFile=C:\\sqlsilent.ini /INDICATEPROGRESS=False"
  args:
    executable: cmd
    chdir: c:\
    creates: C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER
