---
- name: Download PsTools
  ansible.windows.win_get_url:
    dest: "{{ ansible_env.TEMP }}\\pstools.zip"
    url: "https://download.sysinternals.com/files/PSTools.zip"

- name: Extract PSTools
  community.windows.win_unzip:
    src: "{{ ansible_env.TEMP }}\\pstools.zip"
    dest: "{{ ansible_env.TEMP }}\\pstools"
    rm: true

- name: Install SQL 2019
  community.windows.win_psexec:
    command: "{{ disk_image_out.mount_paths[0] }}setup.exe /Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS /ENU /UPDATEENABLED=false /FEATURES=SQLENGINE,Conn /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD={{ mssql_password }} /AGTSVCSTARTUPTYPE=automatic /BROWSERSVCSTARTUPTYPE=automatic /SQLSYSADMINACCOUNTS={{ mssql_username }} /SQLBACKUPDIR=C:\\Backup /SQLUSERDBDIR=C:\\Databases /SQLUSERDBLOGDIR=C:\\UserDatabases" # noqa: yaml[line-length]
    priority: high
    executable: "{{ ansible_env.TEMP }}\\pstools\\PsExec.exe"
