---
- name: Install required DSC module
  community.windows.win_psmodule:
    name: SqlServerDsc
    state: present

- name: Install SQL 2019
  ansible.windows.win_dsc:
    resource_name: SqlSetup
    InstanceName: MSSQLServer
    SourcePath: '{{ disk_image_out.mount_paths[0] }}'
    Features: SQLENGINE
    InstallSharedDir: 'C:\Program Files\Microsoft SQL Server'
    SQLSysAdminAccounts:
      - '{{ mssql_username }}'
    SQLSvcAccount_username: '{{ mssql_username }}'
    SQLSvcAccount_password: '{{ mssql_password }}'
    AgtSvcAccount_username: '{{ mssql_username }}'
    AgtSvcAccount_password: '{{ mssql_password }}'
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_password: '{{ mssql_password }}'
  register: sql_install
