---
- name: Set Windows server tcpip parameters
  hosts: all
  gather_facts: true

  tasks:
    - name: Change tcpip parameter
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnablePMTUDiscovery
        data: 1
        type: dword

    - name: Change tcpip parameter
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnablePMTUBHDetect
        data: 1
        type: dword

    - name: Get interfaces
      ansible.windows.win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\
      register: interface_ids

    - name: Report interface IDs
      ansible.builtin.debug:
        var: interface_ids

    - name: Set mtu size
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{{ item }}
        name: MTU
        data: 4096
        type: dword
      loop: "{{ interface_ids.sub_keys }}"
